package exportdest

import (
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

func manifestOutcomes(path string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	var manifest struct {
		Cases []fixture `json:"cases"`
	}
	if err := json.Unmarshal(data, &manifest); err != nil {
		return err
	}
	if len(manifest.Cases) == 0 {
		return errors.New("empty fixture manifest")
	}
	seen := map[string]bool{}
	for _, c := range manifest.Cases {
		if seen[c.ID] {
			return errors.New("duplicate fixture ID")
		}
		seen[c.ID] = true
		if !c.Valid && sentinels()[c.Error] == nil {
			return errors.New("unknown fixture sentinel")
		}
		if err := fixtureMismatch(c); err != nil {
			return err
		}
	}
	return nil
}

func TestSchemaMutationCoverage(t *testing.T) {
	// The temporary manifest switch exercises the drift harness's rejection path.
	path := fixturePath
	if alternate := os.Getenv("EXPORTDEST_DRIFT_MANIFEST"); alternate != "" {
		path = alternate
	}
	if err := manifestOutcomes(path); err != nil {
		t.Fatal(err)
	}
	cases := readFixtures(t)
	cases[0].Valid = false
	cases[0].Error = "ErrCommon"
	data, err := json.Marshal(struct {
		Version int       `json:"version"`
		Cases   []fixture `json:"cases"`
	}{1, cases})
	if err != nil {
		t.Fatal(err)
	}
	dir, err := os.MkdirTemp("", "exportdest-drift-")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { os.RemoveAll(dir) })
	wrong := filepath.Join(dir, "fixtures.json")
	if err := os.WriteFile(wrong, data, 0600); err != nil {
		t.Fatal(err)
	}
	if err := manifestOutcomes(wrong); err == nil {
		t.Fatal("drift harness accepted a changed expectation")
	}
	// These outcomes are literals from the spec, not generated by Validate.
	mutations := []struct {
		a, path string
		value   any
		want    error
	}{
		{"splunk_hec", "spec.type", "unknown", ErrAdapter},
		{"splunk_hec", "spec.enabled", nil, ErrCommon},
		{"splunk_hec", "spec.endpoint", "udp://a.example:1", ErrCombination},
		{"splunk_hec", "spec.credentialRef", "secret://inline", ErrCommon},
		{"splunk_hec", "spec.tls", nil, ErrCommon},
		{"splunk_hec", "spec.filter.classes", []any{"raw"}, ErrCommon},
		{"splunk_hec", "spec.projection.drop", []any{"metadata"}, ErrCommon},
		{"splunk_hec", "spec.repeats", "unknown", ErrCommon},
		{"splunk_hec", "spec.audit", nil, ErrCommon},
		{"splunk_hec", "spec.archive", true, ErrCombination},
		{"splunk_hec", "spec.batch.maxBytes", float64(67108865), ErrCommon},
		{"splunk_hec", "spec.inflight", float64(17), ErrCommon},
	}
	covered := map[string]bool{}
	for _, c := range mutations {
		r := base(c.a)
		put(r, strings.Split(c.path, "."), c.value)
		expect(t, r, c.want)
		covered[strings.Split(c.path, ".")[1]] = true
	}
	for _, category := range []string{"type", "enabled", "endpoint", "credentialRef", "tls", "filter", "projection", "repeats", "audit", "archive", "batch", "inflight"} {
		if !covered[category] {
			t.Fatalf("missing common coverage category: %s", category)
		}
	}
	authCoverage := map[string]bool{}
	for _, f := range enumFields() {
		if !strings.HasSuffix(f.path, ".auth") {
			continue
		}
		for _, mode := range f.values {
			r := modeResource(f.adapter, f.path, mode)
			expect(t, r, nil)
			s := spec(r)
			if _, ok := s["credentialRef"]; ok {
				delete(s, "credentialRef")
			} else {
				s["credentialRef"] = "credential"
			}
			expect(t, r, ErrCombination)
			authCoverage[f.adapter+"/"+mode] = true
		}
	}
	for _, category := range []string{"elasticsearch/api_key", "elasticsearch/basic", "elasticsearch/mtls", "opensearch/basic", "opensearch/mtls", "opensearch/sigv4", "otlp/bearer", "otlp/mtls", "otlp/headers", "loki/basic", "loki/bearer", "sentinel/certificate", "sentinel/client_secret", "kafka/mtls", "kafka/scram_sha_256", "kafka/scram_sha_512", "kafka/plain", "kafka/oauthbearer", "s3/access_key", "s3/workload"} {
		if !authCoverage[category] {
			t.Fatalf("missing auth coverage category: %s", category)
		}
	}
	for _, a := range []string{"splunk_hec", "syslog", "connector"} {
		r := base(a)
		expect(t, r, nil)
		if a == "splunk_hec" {
			delete(spec(r), "credentialRef")
		} else {
			spec(r)["credentialRef"] = "credential"
		}
		expect(t, r, ErrCombination)
	}
}

func declared(t testing.TB, err error) {
	t.Helper()
	if err == nil {
		return
	}
	for _, sentinel := range sentinels() {
		if err == sentinel {
			return
		}
	}
	t.Fatal("undeclared error")
}

func boundarySeeds() []map[string]any {
	var seeds []map[string]any
	for _, bounds := range numberFields() {
		for _, n := range []float64{bounds.min, bounds.max} {
			r := base(bounds.adapter)
			put(r, strings.Split(bounds.path, "."), n)
			seeds = append(seeds, r)
		}
	}
	r := base("splunk_hec")
	spec(r)["endpoint"] = exactEndpoint(2048)
	seeds = append(seeds, r)
	r = base("splunk_hec")
	r["metadata"].(map[string]any)["description"] = strings.Repeat("界", 1024)
	spec(r)["filter"] = map[string]any{"condition": strings.Repeat("界", 4096)}
	seeds = append(seeds, r)
	r = base("splunk_hec")
	spec(r)["credentialRef"] = strings.Repeat("a", 63)
	seeds = append(seeds, r)
	r = base("s3")
	spec(r)["s3"].(map[string]any)["prefix"] = exactPrefix(256)
	seeds = append(seeds, r)
	return seeds
}

func FuzzValidate(f *testing.F) {
	for _, c := range readFixtures(f) {
		data, err := json.Marshal(c.Resource)
		if err != nil {
			f.Fatal(err)
		}
		f.Add(data)
	}
	for _, r := range boundarySeeds() {
		expect(f, r, nil)
		data, err := json.Marshal(r)
		if err != nil {
			f.Fatal(err)
		}
		f.Add(data)
	}
	for _, data := range [][]byte{nil, []byte("null"), []byte("[0]"), []byte("!"), []byte(`{"kind":"ExportDestination"}`)} {
		f.Add(data)
	}
	f.Fuzz(func(t *testing.T, data []byte) {
		if len(data) > 262144 {
			return
		}
		var resource any
		if json.Unmarshal(data, &resource) != nil {
			return
		}
		before := clone(resource)
		first := Validate(resource)
		second := Validate(resource)
		declared(t, first)
		if first != second {
			t.Fatal("nondeterministic error identity")
		}
		if !reflect.DeepEqual(before, resource) {
			t.Fatal("input mutated")
		}
	})
}

type hostileStringer struct{}

func (hostileStringer) String() string { panic("unsupported values must not be formatted") }

// decodedTree injects defects whose expected stage is independent of Validate.
// Its cyclic trees never reach a JSON marshal or a deep-copy oracle.
func decodedTree(data []byte) (any, error) {
	var mode byte
	if len(data) > 0 {
		mode = data[0]
	}
	switch mode % 16 {
	case 0:
		depth := 0
		if len(data) > 1 {
			depth = int(data[1] % 14)
		}
		want := ErrResource
		if depth > 12 {
			want = ErrLimits
		}
		return nested(depth, nil), want
	case 1:
		m := map[string]any{}
		m["self"] = m
		return m, ErrLimits
	case 2:
		a := make([]any, 1)
		a[0] = a
		return a, ErrLimits
	case 3:
		r := base("splunk_hec")
		r["kind"] = "bad"
		r["z"] = int(1)
		return r, ErrInput
	case 4:
		return map[string]any(nil), ErrInput
	case 5:
		r := base("splunk_hec")
		r["kind"] = "bad"
		r["z"] = string([]byte{255})
		return r, ErrInput
	case 6:
		return map[string]any{string([]byte{255}): hostileStringer{}}, ErrInput
	case 7:
		return map[string]any{strings.Repeat("a", 262144) + string([]byte{255}): hostileStringer{}}, ErrLimits
	case 8:
		return make([]any, 8192), ErrLimits
	case 9:
		return make([]any, 8193), ErrLimits
	case 10:
		r := base("splunk_hec")
		n := 0
		if len(data) > 1 {
			n = int(data[1])
		}
		spec(r)["filter"] = map[string]any{"condition": strings.Repeat("a", n)}
		return r, nil
	case 11:
		return nil, ErrResource
	case 12:
		r := base("splunk_hec")
		r["kind"] = "bad"
		r["z"] = nested(13, nil)
		return r, ErrLimits
	case 13:
		return map[string]any{"a": string([]byte{255}), "z": strings.Repeat("a", 262145)}, ErrInput
	case 14:
		return map[string]any{"a": strings.Repeat("a", 262145), "z": string([]byte{255})}, ErrLimits
	default:
		return hostileStringer{}, ErrInput
	}
}

func FuzzDecoded(f *testing.F) {
	for _, c := range readFixtures(f) {
		data, err := json.Marshal(c.Resource)
		if err != nil {
			f.Fatal(err)
		}
		f.Add(data)
	}
	for mode := range 16 {
		f.Add([]byte{byte(mode), 13})
	}
	f.Add([]byte{0, 12})
	f.Add([]byte{0, 0})
	f.Add([]byte{10, 255})
	f.Fuzz(func(t *testing.T, data []byte) {
		if len(data) > 262144 {
			return
		}
		resource, want := decodedTree(data)
		first := Validate(resource)
		second := Validate(resource)
		declared(t, first)
		if first != second {
			t.Fatal("nondeterministic error identity")
		}
		if !errors.Is(first, want) {
			t.Fatalf("preflight got %v, want %v", first, want)
		}
	})
}
